### ISSUE TITLE
make lib and /lib

### ISSUE THREAD

**Issue by jknox13** [uwhpsc-2016/homework3#6]
when I type `make lib` into the command line I get the following:

``` c
gcc-5 --shared -fopenmp src/integrate.o -o lib/libhomework3.so
/usr/bin/ld: cannot open output file lib/libhomework3.so: No such file or directory
collect2: error: ld returned 1 exit status
Makefile:41: recipe for target 'libhomework3.so' failed
make: *** [libhomework3.so] Error 1
```

Is this because there is no /lib directory in the Homework 3 repo?

**Comment by jknox13** [comment]
Also in `Makefile`:

``` c
# compiler settings
CC=gcc-5
```

Does the `-5` have anything to do with using openMP? I remember in class you used `gcc-5` on your computer because you downloaded gcc to use on your machine or something like that. Could this be causing any problems?

**Comment by gmikel** [comment]
I ended up creating the /lib directory to get around this issue for now.

See this issue for Homework 2: https://github.com/uwhpsc-2016/homework2/issues/5

**Comment by akihis2** [comment]
I don't think using gcc-5 instead of gcc has any related issues. On sage math cloud, it still calls gcc 5.2.1 using either command anyway, so you should be able to use either interchangeably. If you are running it on your own machine, then I can't say for sure, but on my machine (running Ubuntu-Mate 16.04) I seem to be able to use gcc and gcc-5 interchangeably without any issue.

**Comment by jknox13** [comment]
Creating the /lib directory totally works

**Comment by jknox13** [comment]
Creating the /lib directory totally works

**Comment by cswiercz** [comment]
This was addressed in a patch. See #5 for instructions on obtaining the fix.
